# Generated by Django 3.2.4 on 2021-06-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_bookingmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='date',
        ),
    ]
