# Generated by Django 3.2.4 on 2021-06-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
